[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_files = [
    "Cargo.toml:^version",
]
pre_bump_hooks = [
    "cargo generate-lockfile || echo 'cargo does not exist'",
    "sed -i 's/^version = 4/version = 3/' Cargo.lock",
    "nix run github:cargo2nix/cargo2nix -- -o || echo 'nix does not exist'"
]
version_type = "semver"
version_provider = "cargo"
update_changelog_on_bump = true
major_version_zero = true
